### ISSUE TITLE
failed to install rancheros on VirtualBox

### ISSUE THREAD

**Issue by ifeiteng** [rancherio/os#88] opened 2015-03-18 02:23 UTC
first, the `rancheros-install` is not exist, i pull it from `/scripts/dockerimages/scripts/rancheros-install`
then, i use `sudo rancheros-install -d /dev/sda -c ./cloud_data.yml -v v0.1.2 -t generic`
it show me `The file /dev/sda1 is not exist and no size was specified`

**Comment by ibuildthecloud** [comment] 2015-03-18 05:58
Sorry about that.  We just about to cut a release of RancherOS that includes this script but we merged the README to master.  So the docs are not in sync with the latest release.

**Comment by wblankenship** [comment] 2015-03-18 13:41
Good to know! I thought I was loosing my mind. :smile:

**Comment by cloudnautique** [comment] 2015-03-18 15:37
@ifeiteng do you have any more of the output you'd be willing to share via a gist or something?

**Comment by fernando-cloudster** [comment] 2015-03-18 16:59
Any ETA on the new release? Or any other way to install on vbox/vmware?

**Comment by cloudnautique** [comment] 2015-03-18 17:05
@fernando-cloudster Soon! 

If you are feeling adventurous: [rancherio/os-installer](https://github.com/rancherio/os-installer) outlines the processes.

**Comment by fernando-cloudster** [comment] 2015-03-18 17:07
Hah! here I go :D thanks!

**Comment by fernando-cloudster** [comment] 2015-03-18 19:14
Guess I'll join the OP on waiting, unless anybody got some ideas for me.

The steps to install on the disk were actually really easy, I was expecting a lot of pain :dancers: 

```
sudo system-docker run --privileged --net=host -it --entrypoint=/scripts/set-disk-partitions rancher/os-installer:v0.1.2 /dev/sda
sudo system-docker run --privileged --net=host -it --volumes-from=user-volumes rancher/os-installer:v0.1.2 -d /dev/sda -t generic -c /opt/cloud 
```
and boom its installed, so I guess the issue is in my cloud-init file.

```
#cloud-config
users:
  - name: myuser
    passwd: $1$cccIdjm...(generated with openssl passwd -1)
    groups:
      - sudo
      - docker
      - rancher
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1...(my pubkey)
```
any ideas on what I did wrong?

**Comment by cloudnautique** [comment] 2015-03-18 20:04
@fernando-cloudster We support a limited subset of cloud-init at the moment:
https://github.com/rancherio/os#cloud-init

Glad the raw container worked for you. The wrapper script adds some safety guards... like warning you its going to format/partition your disk :)

**Comment by fernando-cloudster** [comment] 2015-03-18 20:10
@cloudnautique I tried using only

```
#cloud-config
ssh_authorized_keys:
  - ssh-rsa aasd.. myuser@box
```

but what do I ssh into the box as?
ssh myuser@rancherip?
(tried root/rancher, no luck)

I have the feeling I should be going to sleep cause I might be missing something really stupid :)

**Comment by cloudnautique** [comment] 2015-03-18 20:50
No, the process isn't documented all that well... and the guts are even less so :)

It is very particular about where the file needs to be. The wrapper will make this easier, the file needs to called: `user_config.yml`
It needs to be in an /opt or /home path because those are sharable between the user volumes and system volumes. So, to emulate the wrapper behavior, create `-c /opt/user_config.yml`

I believe what is happening, is that the file is being copied, but not being loaded because of the name... based on your command a few posts ago... it looks like your using -c /opt/cloud 

If it loads, then the keys are added to the **rancher** user.

**Comment by fernando-cloudster** [comment] 2015-03-19 12:35
Yup, did all that, no luck for me :) I'll wait for the installer I guess. Thanks for trying @cloudnautique

**Comment by ibuildthecloud** [comment] 2015-03-19 22:41
Release ETA is "very soon."  You can try the rc build here https://github.com/rancherio/os/releases/download/v0.2.0-rc2/rancheros.iso

**Comment by ibuildthecloud** [comment] 2015-03-25 10:47
As of release v0.2.1 installation to disk is now supported.  It's documented at https://github.com/rancherio/os#installing-to-disk

**Closed by ibuildthecloud** 2015-03-25 10:47 UTC
