### ISSUE TITLE
Trouble starting services on boot in RancherOS v0.2.1

### ISSUE THREAD

**Issue by imikushin** [rancherio/os#106] opened 2015-03-26 14:34 UTC
`/opt/rancher/bin/start.sh` doesn't seem to make it: vagrant up just stalls and I don't know what's going on. 
`/opt/rancher/bin/start.sh`:
```bash
#!/bin/sh
nohup /opt/rancher/bin/do-start.sh >/var/log/start.log 2>&1 &
```
`/opt/rancher/bin/do-start.sh`:
```bash
#!/bin/sh
set -x -e
docker stop nginx && docker rm nginx && :
docker run -d --name=nginx -p=8080:80 nginx
```

Both `start.sh` and `do-start.sh` are executable.

OS appears to hang on after `Running [7/13] cloud-init-pre`:
![os-vagrant_rancher-01_1427374830498_34855](https://cloud.githubusercontent.com/assets/931932/6848286/26c21126-d3ee-11e4-8c73-4b962b9a29b8.png)

**Comment by ibuildthecloud** [comment] 2015-03-26 14:45
If  /opt/rancher/bin/start.sh fails it shouldn't fail the boot, but  /opt/rancher/bin/start.sh is actually executed by the console container.  So in this situation the reason it isn't booting is not related to you script.  If cloud-init-pre is hung that means it can't talk to the cloud config data source.  In the Vagrant setup there is a file `/var/lib/rancher/conf/user_config.yml`.  If you delete that file, the boot will hang forever.  You have to also edit rancher.yml and remove the reference to it.  This is a bug and should be fixed.

**Comment by ibuildthecloud** [comment] 2015-03-26 14:46
I created #107 to track this issue.

**Comment by imikushin** [comment] 2015-03-26 15:11
The file is there. I didn't delete it, just added `start.sh`. To reproduce,
just add my `start.sh` and `do-start.sh`

**Comment by imikushin** [comment] 2015-03-26 17:11
@ibuildthecloud, actually, you are right: I just tried to reproduce this anew and it worked. 
OK, this got the boot to hang (not forever, just for a **very** long time):
```bash
# rancherctl c get cloud_init.datasources
- file:/home/rancher/cloud-init.sh
```
`cloud-init.sh` being an executable script:
```bash
#!/bin/sh
set -x -e

mkdir -p /opt/rancher/bin

cat <<EOF >/opt/rancher/bin/start.sh
#!/bin/sh
nohup /opt/rancher/bin/do-start.sh >/var/log/start.log 2>&1 &
EOF

chmod +x /opt/rancher/bin/start.sh

cat <<EOF >/opt/rancher/bin/do-start.sh
#!/bin/sh
set -x -e
docker stop nginx && docker rm nginx && :
docker run -d --name=nginx -p=8080:80 nginx
EOF

chmod +x /opt/rancher/bin/do-start.sh
```

**Comment by imikushin** [comment] 2015-03-26 17:43
Hangs exactly the same way after this: 
```bash
rancherctl c set cloud_init.datasources [file:/home/rancher/my_config.yml]
```
`my_config.yml` contains:
```yml
#cloud-config
write_files:
- path: /opt/rancher/bin/start.sh
  permissions: 0755
  owner: root
  content: |
    #!/bin/sh
    nohup /opt/rancher/bin/do-start.sh >/var/log/start.log 2>&1 &
- path: /opt/rancher/bin/do-start.sh
  permissions: 0755
  owner: root
  content: |
    #!/bin/sh
    set -x -e
    docker stop nginx && docker rm nginx && :
    docker run -d --name=nginx -p=8080:80 nginx
```

**Comment by ibuildthecloud** [comment] 2015-03-26 18:16
@imikushin Can you put the file into /var/lib/rancher/conf?  I know this is confusing, but cloud-init doesn't have access to /home.

**Comment by ibuildthecloud** [comment] 2015-03-26 18:18
@imikushin I have created #108 for this, cloud-init should have access, but it is not setup that way.

**Comment by imikushin** [comment] 2015-03-26 18:45
Thanks, @ibuildthecloud, placing the file into `/var/lib/rancher/conf` helped! 
Now, there's a problem with YAML cloud-config: `write_file` instruction doesn't seem to work. But the other option (`cloud-init.sh`) does run all right.

**Comment by ibuildthecloud** [comment] 2015-03-26 18:53
No write files, should work.  let me try your cloud config and try to reproduce.

**Comment by deniseschannon** [comment] 2015-04-30 21:35
@imikushin Closing this as logic is in console. Let's discuss if it's still not working.

**Closed by deniseschannon** 2015-04-30 21:35 UTC
