### ISSUE TITLE
userdata on EC2

### ISSUE THREAD

**Issue by runseb** [rancherio/os#66] opened 2015-03-03 10:31 UTC
It seems that if we pass some user-data to start a rancheros instance on EC2, a #cloud-config file will conflict with the keypair being used. Hence using the keypair to ssh into the instance fails.

I have not checked logs, but without specifying #cloud-config user data, ssh using the keypair works.

**Comment by ibuildthecloud** [comment] 2015-03-03 14:06
@sidharthamani Can you look into this?

**Comment by wlan0** [comment] 2015-03-04 19:19
@runseb I'm not able to reproduce this issue. Could you please specify steps to reproduce this issue?

**Comment by runseb** [comment] 2015-03-04 19:21
@wlan0 I will try again, but that was using my playbook https://github.com/runseb/ansible-rancher
if you check the roles/rancher/tasks/create_vm.yml file I have had to uncomment the user_data line to get the keypair working.

**Comment by ibuildthecloud** [comment] 2015-03-08 05:46
@runseb I see what your issue is now.  Looking at your playbook I realize that your setting the user-data to a script and not a '#cloud-config'.  So there definitely is an issue there if the user data is a script we do not read the EC2 meta data.  Our previous attempts to reproduce this we were setting the user-data to a cloud-config.

ping @wlan0

**Comment by runseb** [comment] 2015-03-08 18:31
@ibuildthecloud I was trying to run docker run rancher/server on start. and it did not seem that your cloudinit supported run_cmd, so I switched to bash for cloudinit.

**Comment by wlan0** [comment] 2015-04-30 22:32
verified that this is fixed. 

@deniseschannon This can be closed.

**Comment by deniseschannon** [comment] 2015-05-01 00:16
@runseb if this is still an issue, please re-open, but it looks as if it's fixed as of v0.3.0

**Closed by deniseschannon** 2015-05-01 00:16 UTC
