### ISSUE TITLE
Error pulling image - ApplyLayer exit status 1: xz: corrupted data

### ISSUE THREAD

**Issue by dmp1ce** [rancherio/os#124] opened 2015-04-01 21:08 UTC
I have a Vagrant version of RancherOS running and I'm trying to pull a particular image but I keep getting an error. The image I am trying to pull is `patrickod/docker-tor`. The error is:

```
$ docker pull patrickod/docker-tor
Pulling repository patrickod/docker-tor
be14dfba2a7f: Error pulling image (latest) from patrickod/docker-tor, ApplyLayer exit status 1: xz: corrupted data
 stdout: {"layerSize":128007367}dependent layers 
FATA[0071]  stderr:    
```

I have been able to pull other images, so I'm not sure what is different about this one.

**Comment by cloudnautique** [comment] 2015-04-02 05:19
I'm able to reproduce as well. Curious if your other tests have been on a newer CoreOS release? It downloaded fine on the Boot2docker image. Will need to troubleshoot more.

**Comment by dmp1ce** [comment] 2015-04-02 14:45
I did not test on CoreOS, but I run this image on Arch Linux and it works fine.

**Comment by dmp1ce** [comment] 2015-04-02 14:58
I've also tested on Ubuntu 14.10 with no problems.

**Comment by ibuildthecloud** [comment] 2015-04-02 21:57
@dmp1ce This is because we haven't packaged xz.  Sorry for the oversight.  Older docker images were xz compressed, but most today are not.

**Comment by dmp1ce** [comment] 2015-04-03 03:51
No problem. Are you guys planning on supporting xz compressed images?

**Comment by ibuildthecloud** [comment] 2015-04-03 10:30
Yes we will.  We will add XZ to next weeks release.

**Comment by deniseschannon** [comment] 2015-04-13 03:16
As of v0.3.0-rc1, this is working. @dmp1ce I'm going to close this issue. Please re-open if you have more questions.

**Closed by deniseschannon** 2015-04-13 03:16 UTC
